GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/1

###

GET http://localhost:3001/api/persons/69edb10706075eb87427ba0e

###

GET http://localhost:3001/api/persons/507f1f77bcf86cd799439011

###

DELETE http://localhost:3001/api/persons/507f1f77bcf86cd799439011

###

DELETE http://localhost:3001/api/persons/2

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "John Doe",
    "number": "050-123456"
}

###

PUT http://localhost:3001/api/persons/69edc044857096746f83aa91
Content-Type: application/json

{
    "number": "baz"
}
